### ISSUE TITLE
Submodule error while updating

### ISSUE THREAD

**Issue by nkhedekar** [robowork/autonomous_mobile_manipulation#1]
Submodules that were initialized but later made as source installations were not completely removed from the repository. The error message for each of them is of the form: 

```bash
warning: Could not find section in .gitmodules where path=deps/libpointmatcher
```

A fix would be to run `git rm deps/<name>`

Refer: https://stackoverflow.com/questions/4185365/no-submodule-mapping-found-in-gitmodule-for-a-path-thats-not-a-submodule

**Comment by papachric** [comment]
They were leftovers (there were actually a number of them), removed them now. Thanks.
