### ISSUE TITLE
Minor Bug in get_ik.py

### ISSUE THREAD

**Issue by mihirk284** [robowork/autonomous_mobile_manipulation#14]
In [this line](https://github.com/robowork/autonomous_mobile_manipulation/blob/c64c34885e650100dd9487bf3d99ba91292a0250/robowork_planning/scripts/get_ik.py#L180), the code should be:
`if(response.error_code.val == 1):`

The function is currently comparing the error code object with the value 1 and is always false.

CC: @Pratiquea

**Comment by Pratiquea** [comment]
Right. it should be `if(response.error_code.val == 1):`
