### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by nkhedekar** [robowork/autonomous_mobile_manipulation#2]
The instructions for rtabmap are: 

# RTABMAP
cd $HOME/autonomous_mobile_manipulation_ws && git clone https://github.com/introlab/rtabmap && cd rtabmap && git checkout 0.20.3-melodic && cd build
CMAKE_PREFIX_PATH=$HOME/autonomous_mobile_manipulation_ws/devel:$CMAKE_PREFIX_PATH cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/autonomous_mobile_manipulation_ws/devel ..
make -j 12 && make install 

It should be: 

# RTABMAP
cd $HOME/autonomous_mobile_manipulation_ws && git clone https://github.com/introlab/rtabmap && cd rtabmap && git checkout 0.20.3-melodic && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/autonomous_mobile_manipulation_ws/devel ..
make -j 12 && make install

**Comment by papachric** [comment]
No that's actually there to make it search for cmake modules under the devel space $HOME/autonomous_mobile_manipulation_ws/devel
They were the versions installed during the previous steps. 
Without that it will search for e.g. the gtsam etc. cmake config files under the main cmake module locations and use those versions and libraries to build rtabmap.

**Comment by papachric** [comment]
Let me know if you mean something else otherwise i'll close it

**Comment by nkhedekar** [comment]
Yep, I meant this line specifically:

```bash
CMAKE_PREFIX_PATH=$HOME/autonomous_mobile_manipulation_ws/devel:$CMAKE_PREFIX_PATH cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/autonomous_mobile_manipulation_ws/devel ..
```

I got an error while doing this but that was probably due to a typo. That made me think that setting an environment variable and calling cmake in the same line without an `&&` or some other special function was the cause. I just tried running this on a dummy repo and it worked. My bad.
