### ISSUE TITLE
Could not build RTABMAP because of missing g2o include

### ISSUE THREAD

**Issue by Bscout2011** [robowork/autonomous_mobile_manipulation#6]
The following command must be run on my computer before building RTABMAP (solution provided by @papachric ):
`CMAKE_PREFIX_PATH cmake -DCMAKE_BUILD_TYPE=Release -DCSPARSE_INCLUDE_DIR=$HOME/autonomous_mobile_manipulation_ws/g2o/EXTERNAL/csparse -DCMAKE_INSTALL_PREFIX=$HOME/autonomous_mobile_manipulation_ws/devel ..
`

**Comment by papachric** [comment]
Thanks merged now.

Note, this is because for whatever reason RTABMAP is not able to locate the csparse provided by g2o as it is installed in the devel space
