### ISSUE TITLE
.gazebo/models doesn't exist

### ISSUE THREAD

**Issue by PlayWeird** [robowork/autonomous_mobile_manipulation#9]
when I run the command "cp -r gazebo_resources/models/* $HOME/.gazebo/models/" I get the error that "$HOME/.gazebo/models/" does not exist. Should I create the "models" directory in the ".gazebo" directory or should it have been created automatically?

**Comment by papachric** [comment]
Do you have gazebo installed? I'm not 100% sure but if you do and you've launched it at least once the `models` directory should exist. Anyhow, if it doesn't you can safely create it yourself yes.

**Comment by PlayWeird** [comment]
I added the folder. It seems to be working.
